async function main() {
  console.log('hello')
}
main().catch((e) => console.error(e))
